/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      'dirt-white': '#F4F1EB',
      'primary-black': '#141513',
      white: '#FFFFFF',
      grey: '#D1D0CD',
      red: '#FF8A71',
    },
    fontSize: {
      header: ['48px', '52.8px'],
      title: ['36px', '39.6px'],
      xs: ['12px', '16px'],
      sm: ['14px', '20px'],
      md: ['16px', '24px'],
      lg: ['20px', '26px'],
      xl: ['26px', '31px'],
    },
    letterSpacing: {
      tighter: '-2px',
      tight: '-1px',
      normal: '-0.5px',
      base: '-1%',
    },
    width: {
      1: '0.25rem',
      'listing-card': '295px',
      header: '343px',
      auto: 'auto',
      full: '100%',
      'info-card': '335px',
      15: '15%',
      20: '20%',
      25: '25%',
      30: '30%',
      40: '40%',
      45: '45%',
      50: '50%',
      55: '55%',
      60: '60%',
      70: '70%',
    },
    height: {
      auto: 'auto',
      5: '1.5rem',
      12: '3rem',
      footer: '580px',
      header: '106px',
      amenities: '140px',
      'listing-card': '748px',
      'listing-card-image': '290px',
      'small-listing-card': '204px',
      'info-card': '206px',
    },
    padding: {
      2: '0.20rem',
      3: '0.5rem',
      '3/4': '0.75rem',
      4: '1rem',
      '4/5': '1.25rem',
      5: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      16: '4rem',
      18: '4.5rem',
      19: '5rem',
    },
    borderRadius: {
      sm: '10px',
      lg: '20px',
    },
    borderWidth: {
      'one-half': '1.5px',
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
